version: '2.1'

services:

  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
  
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.1.0
    container_name: elasticsearch_exporter
    command:
     - '--es.uri=http://elasticsearch:9200'
    ports:
    - "127.0.0.1:9114:9114"
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  nginxexporter:
    image: nginx/nginx-prometheus-exporter:0.8.0
    container_name: nginxexporter
    ports:
      - 9113:9113
    command:
      - -nginx.scrape-uri
      - http://nginx:80/index.html
      - -nginx.retries=10
      - -web.telemetry-path=/prometheus
    network_mode: host
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
  

